services:
  postgres-db:
    image: postgres:16-alpine
    container_name: concursos-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - concursos-network

  app:
    build: .
    container_name: api-concursos-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - API_SECURITY_TOKEN_SECRET=${API_SECURITY_TOKEN_SECRET}
    depends_on:
      - postgres-db
    networks:
      - concursos-network

volumes:
  postgres_data:

networks:
  concursos-network:
    driver: bridge